// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectContext } from "./ProjectContext.js";

export type GenerateRunCommandsRequest = { context: ProjectContext, };