// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LightTraceType } from "./LightTraceType";
import type { Position } from "./Position";

export type LightTrace = { trace_id: string, start_pos: Position, end_pos: Position, parent_id: string, timestamp: number, trace_type: LightTraceType, };
