// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trace } from "./Trace.js";

export type PushTracesRequest = { traces: Array<Trace>, };