// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandWithPath } from "./CommandWithPath.js";

export type RunCommands = { project: Array<CommandWithPath>, file: Array<CommandWithPath>, };