// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sorted list structure optimized for insertions near the end
 */
export type SortedList<T> = { items: Array<T>, };
