// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { TraceType } from "./TraceType";

export type Trace = { trace_id: string, start_pos: Position, end_pos: Position, parent_id: string, timestamp: number, trace_type: TraceType, };
