// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EcmaImportStyle } from "./EcmaImportStyle";

export type CodeInstrumentationBatchRequest = { files_contents: Array<string>, files_paths: Array<string>, project_root: string, project_import_style: EcmaImportStyle | null, };
