// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Family } from "./Family";
import type { LightTrace } from "./LightTrace";
import type { SortedList } from "./SortedList";
import type { Span } from "./Span";

export type ConstructionTraceTree = { orphan_families: { [key in string]: Family }, orphan_families_with_no_indirect_parent: Array<string>, spans: { [key in string]: Span }, spans_with_indef_end: Array<string>, traces: SortedList<LightTrace>, min_ts: number, max_ts: number, };
