// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndirectParent } from "./IndirectParent";
import type { Timestamp } from "./Timestamp";

export type Family = { start: Timestamp, end: Timestamp, indirect_parent: IndirectParent | null, };
