// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedFamily } from "./LoadedFamily";

export type Family = { "type": "Virtual" } & string | { "type": "Loaded" } & LoadedFamily;
