// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";
import type { SpanSummary } from "./SpanSummary";

export type LoadedFamily = { id: string, spans: Array<Span>, summaries: Array<SpanSummary>, span: Span | null, summary: SpanSummary | null, };
