// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemCommand } from "./SystemCommand.js";

export type ProjectContext = { workspace_path: string, os: string, files_tree: string, important_workspace_files: Array<string>, important_workspace_file_content: { [key in string]: string | null }, system_commands: Array<SystemCommand>, current_focused_file_path: string | null, current_focused_file_content: string | null, };