// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedSpan } from "./LoadedSpan";
import type { VirtualSpan } from "./VirtualSpan";

export type Span = { "type": "Virtual" } & VirtualSpan | { "type": "Loaded" } & LoadedSpan;
