// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

export type SpanSummary = { filepath: string, expression_range: Range, is_error: boolean, value: string | null, start_timestamp: number, end_timestamp: number, datetime: string, };
