// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

export type Span = { trace_id: string, is_error: boolean, start: Timestamp, end: Timestamp, direct_children: Array<string>, indirect_children_family: [string, number] | null, };
