// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TraceType = "Enter" | { "Exit": { duration_ns: number, return_value: string | null, } } | { "Error": { duration_ns: number, error_message: string, } } | "Legacy";
