// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trace } from "./Trace";

export type VirtualSpan = { enter_trace: Trace, exit_or_error_trace: Trace | null, };
